const net = require('net')
const { parse, resolve } = require('path')

class Request{  //构造请求类
    constructor(p){
        this.method = p.method || 'GET'
        this.host = p.host
        this.port = p.port || 80
        this.path = p.path || '/'
        this.body = p.data
        this.headers = p.headers || Object.create(null)
        if(!this.headers['Content-Type'])
            this.headers['Content-Type'] = "application/x-www-form-urlencoded"

        if(this.headers['Content-Type'] === "application/json")
            this.bodyText = JSON.stringify(this.body)
        else if(this.headers['Content-Type'] === "application/x-www-form-urlencoded")
            this.bodyText = Object.keys(this.body).map(k=>`${k}=${encodeURIComponent(this.body[k])}`).join("&")
        
        this.headers['Content-Length'] = this.bodyText.length
    }

    send(connection){ //将数据发送到服务器·
        return new Promise((resovle, reject)=>{
            const parser = new ResponseParser()
            if(connection){
                connection.write(this.toString())
            }else{
                connection = net.createConnection({
                    host: this.host,
                    port: this.port
                },()=>{
                    console.log(this.toString())
                    connection.write(this.toString())
                })
            }
            connection.on('data', data=>{
                console.log('data:', data.toString())
                parser.receive(data.toString())
                if(parser.isFinised){
                    resolve(parse.response)
                    connection.end()
                }
            })
            connection.on('error', error=>{
                console.error(error)
                reject(error)
                connection.end()
            })
            

            resovle()
        })
    }
    
    toString(){ //按照请求格式封装请求头
        return `${this.method} ${this.path} HTTP/1.1\r
${Object.keys(this.headers).map(k=>`${k}: ${this.headers[k]}`).join('\r\n')}\r
\r
${this.bodyText}`
    }
}

class ResponseParser{
    constructor(){
        this.WAIT_STATUS_LINE = 0
        this.WAIT_STATUS_LINE_END = 1
        this.WAIT_HEADER_NAME = 2
        this.WAIT_HEADER_SPACE = 3
        this.WAIT_HEADER_VALUE = 4
        this.WAIT_HEADER_VALUE_END = 5
        this.WAIT_HEADER_LINE_BLOCK_END = 6
        this.WAIT_BODY= 7
        this.statusLine = ""
        this.headerName = ""
        this.headerValue = ""
        this.headers = {}
        this.status = this.WAIT_STATUS_LINE
    }
    receive(string){
        for(let i=0; i<string.length; i++){
            this.receiveChar(string.charAt(i))
        }
    }
    receiveChar(c){ //状态机实现
        if(this.status === this.WAIT_STATUS_LINE){
            if(c === '\r')
                this.status = this.WAIT_STATUS_LINE_END
            else
                this.statusLine += c
        }else if(this.status === this.WAIT_STATUS_LINE_END){
            if(c === '\n')
                this.status = this.WAIT_HEADER_NAME
        }else if(this.status === this.WAIT_HEADER_NAME){
            if(c === ':')
                this.status = this.WAIT_HEADER_SPACE
            else if(c === '\r')   // 所有的头信息接受完毕，准备进入WAIT_BODY
                this.status = this.WAIT_HEADER_LINE_BLOCK_END
            else
                this.headerName += c
        }else if(this.status === this.WAIT_HEADER_SPACE){
            if(c === ' ')
                this.status = this.WAIT_HEADER_VALUE
        }else if(this.status === this.WAIT_HEADER_VALUE){
            if(c === '\r'){
                this.status = this.WAIT_HEADER_VALUE_END
                this.headers[this.headerName] = this.headerValue
                this.headerName = this.headerValue = ''
            }else
                this.headerValue += c
        }else if (this.status === this.WAIT_HEADER_VALUE_END){
            if(c === '\n')
                this.status = this.WAIT_HEADER_NAME
        }else if(this.status === this.WAIT_HEADER_LINE_BLOCK_END){                
            if(c === '\n')
                this.status = this.WAIT_BODY
        }else if(this.status === this.WAIT_BODY){
            console.log(c)
        }
        
    }
}

void async function(){   //因为里面使用了await，所以需要用async function的IIFE包裹一下
    let request = new Request({
        host: '127.0.0.1',
        port: 8080,
        path: '/',
        headers: {
            "X-Foo": "123456"
        },
        data: {
            "username":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username1":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username2":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username3":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username4":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username5":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username6":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username7":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username8":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username9":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username10":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username11":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username12":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username13":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username14":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username15":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username16":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username17":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username18":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username19":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username20":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username21":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username22":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username23":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username24":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username25":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username26":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username27":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username28":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username29":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username30":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username31":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username32":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username33":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username34":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username35":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username36":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username37":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username38":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username39":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username40":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username42":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username41":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username43":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username44":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username45":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username46":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username47":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username48":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username50":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username60":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username70":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username80":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username90":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "username100":"jasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjasonjason",
            "password":"123456"
        }
    })

    let res = await request.send()
}()